// Genererat från openfootball/worldcup.json (FIFA World Cup 2026).
// 48 lag, 12 grupper om 4, 104 matcher. Tider i lokal tid med UTC-offset.

export const TEAMS = {
  MEX: { code: 'MEX', iso: 'mx', name: 'Mexiko' },
  RSA: { code: 'RSA', iso: 'za', name: 'Sydafrika' },
  KOR: { code: 'KOR', iso: 'kr', name: 'Sydkorea' },
  CZE: { code: 'CZE', iso: 'cz', name: 'Tjeckien' },
  CAN: { code: 'CAN', iso: 'ca', name: 'Kanada' },
  BIH: { code: 'BIH', iso: 'ba', name: 'Bosnien-Hercegovina' },
  QAT: { code: 'QAT', iso: 'qa', name: 'Qatar' },
  SUI: { code: 'SUI', iso: 'ch', name: 'Schweiz' },
  BRA: { code: 'BRA', iso: 'br', name: 'Brasilien' },
  MAR: { code: 'MAR', iso: 'ma', name: 'Marocko' },
  HAI: { code: 'HAI', iso: 'ht', name: 'Haiti' },
  SCO: { code: 'SCO', iso: 'gb-sct', name: 'Skottland' },
  USA: { code: 'USA', iso: 'us', name: 'USA' },
  PAR: { code: 'PAR', iso: 'py', name: 'Paraguay' },
  AUS: { code: 'AUS', iso: 'au', name: 'Australien' },
  TUR: { code: 'TUR', iso: 'tr', name: 'Turkiet' },
  GER: { code: 'GER', iso: 'de', name: 'Tyskland' },
  CUW: { code: 'CUW', iso: 'cw', name: 'Curaçao' },
  CIV: { code: 'CIV', iso: 'ci', name: 'Elfenbenskusten' },
  ECU: { code: 'ECU', iso: 'ec', name: 'Ecuador' },
  NED: { code: 'NED', iso: 'nl', name: 'Nederländerna' },
  JPN: { code: 'JPN', iso: 'jp', name: 'Japan' },
  SWE: { code: 'SWE', iso: 'se', name: 'Sverige' },
  TUN: { code: 'TUN', iso: 'tn', name: 'Tunisien' },
  BEL: { code: 'BEL', iso: 'be', name: 'Belgien' },
  EGY: { code: 'EGY', iso: 'eg', name: 'Egypten' },
  IRN: { code: 'IRN', iso: 'ir', name: 'Iran' },
  NZL: { code: 'NZL', iso: 'nz', name: 'Nya Zeeland' },
  ESP: { code: 'ESP', iso: 'es', name: 'Spanien' },
  CPV: { code: 'CPV', iso: 'cv', name: 'Kap Verde' },
  KSA: { code: 'KSA', iso: 'sa', name: 'Saudiarabien' },
  URU: { code: 'URU', iso: 'uy', name: 'Uruguay' },
  FRA: { code: 'FRA', iso: 'fr', name: 'Frankrike' },
  SEN: { code: 'SEN', iso: 'sn', name: 'Senegal' },
  IRQ: { code: 'IRQ', iso: 'iq', name: 'Irak' },
  NOR: { code: 'NOR', iso: 'no', name: 'Norge' },
  ARG: { code: 'ARG', iso: 'ar', name: 'Argentina' },
  ALG: { code: 'ALG', iso: 'dz', name: 'Algeriet' },
  AUT: { code: 'AUT', iso: 'at', name: 'Österrike' },
  JOR: { code: 'JOR', iso: 'jo', name: 'Jordanien' },
  POR: { code: 'POR', iso: 'pt', name: 'Portugal' },
  COD: { code: 'COD', iso: 'cd', name: 'DR Kongo' },
  UZB: { code: 'UZB', iso: 'uz', name: 'Uzbekistan' },
  COL: { code: 'COL', iso: 'co', name: 'Colombia' },
  ENG: { code: 'ENG', iso: 'gb-eng', name: 'England' },
  CRO: { code: 'CRO', iso: 'hr', name: 'Kroatien' },
  GHA: { code: 'GHA', iso: 'gh', name: 'Ghana' },
  PAN: { code: 'PAN', iso: 'pa', name: 'Panama' },
};

export const GROUPS = [
  { id: 'A', teams: ['MEX', 'CZE', 'KOR', 'RSA'] },
  { id: 'B', teams: ['CAN', 'BIH', 'QAT', 'SUI'] },
  { id: 'C', teams: ['BRA', 'HAI', 'MAR', 'SCO'] },
  { id: 'D', teams: ['USA', 'AUS', 'PAR', 'TUR'] },
  { id: 'E', teams: ['GER', 'CIV', 'CUW', 'ECU'] },
  { id: 'F', teams: ['NED', 'JPN', 'SWE', 'TUN'] },
  { id: 'G', teams: ['BEL', 'EGY', 'IRN', 'NZL'] },
  { id: 'H', teams: ['ESP', 'CPV', 'KSA', 'URU'] },
  { id: 'I', teams: ['FRA', 'IRQ', 'NOR', 'SEN'] },
  { id: 'J', teams: ['ARG', 'ALG', 'AUT', 'JOR'] },
  { id: 'K', teams: ['POR', 'COD', 'COL', 'UZB'] },
  { id: 'L', teams: ['ENG', 'CRO', 'GHA', 'PAN'] },
];

export const MATCHES = [
  { num:   1, stage: 'GROUP', group:  'A', date: '2026-06-11', time: '13:00 UTC-6', venue: 'Mexico City', home: 'MEX', away: 'RSA' },
  { num:   2, stage: 'GROUP', group:  'A', date: '2026-06-11', time: '20:00 UTC-6', venue: 'Guadalajara (Zapopan)', home: 'KOR', away: 'CZE' },
  { num:   3, stage: 'GROUP', group:  'B', date: '2026-06-12', time: '15:00 UTC-4', venue: 'Toronto', home: 'CAN', away: 'BIH' },
  { num:   4, stage: 'GROUP', group:  'D', date: '2026-06-12', time: '18:00 UTC-7', venue: 'Los Angeles (Inglewood)', home: 'USA', away: 'PAR' },
  { num:   5, stage: 'GROUP', group:  'B', date: '2026-06-13', time: '12:00 UTC-7', venue: 'San Francisco Bay Area (Santa Clara)', home: 'QAT', away: 'SUI' },
  { num:   6, stage: 'GROUP', group:  'C', date: '2026-06-13', time: '18:00 UTC-4', venue: 'New York/New Jersey (East Rutherford)', home: 'BRA', away: 'MAR' },
  { num:   7, stage: 'GROUP', group:  'C', date: '2026-06-13', time: '21:00 UTC-4', venue: 'Boston (Foxborough)', home: 'HAI', away: 'SCO' },
  { num:   8, stage: 'GROUP', group:  'D', date: '2026-06-13', time: '21:00 UTC-7', venue: 'Vancouver', home: 'AUS', away: 'TUR' },
  { num:   9, stage: 'GROUP', group:  'E', date: '2026-06-14', time: '12:00 UTC-5', venue: 'Houston', home: 'GER', away: 'CUW' },
  { num:  10, stage: 'GROUP', group:  'F', date: '2026-06-14', time: '15:00 UTC-5', venue: 'Dallas (Arlington)', home: 'NED', away: 'JPN' },
  { num:  11, stage: 'GROUP', group:  'E', date: '2026-06-14', time: '19:00 UTC-4', venue: 'Philadelphia', home: 'CIV', away: 'ECU' },
  { num:  12, stage: 'GROUP', group:  'F', date: '2026-06-14', time: '20:00 UTC-6', venue: 'Monterrey (Guadalupe)', home: 'SWE', away: 'TUN' },
  { num:  13, stage: 'GROUP', group:  'H', date: '2026-06-15', time: '12:00 UTC-4', venue: 'Atlanta', home: 'ESP', away: 'CPV' },
  { num:  14, stage: 'GROUP', group:  'G', date: '2026-06-15', time: '12:00 UTC-7', venue: 'Seattle', home: 'BEL', away: 'EGY' },
  { num:  15, stage: 'GROUP', group:  'H', date: '2026-06-15', time: '18:00 UTC-4', venue: 'Miami (Miami Gardens)', home: 'KSA', away: 'URU' },
  { num:  16, stage: 'GROUP', group:  'G', date: '2026-06-15', time: '18:00 UTC-7', venue: 'Los Angeles (Inglewood)', home: 'IRN', away: 'NZL' },
  { num:  17, stage: 'GROUP', group:  'I', date: '2026-06-16', time: '15:00 UTC-4', venue: 'New York/New Jersey (East Rutherford)', home: 'FRA', away: 'SEN' },
  { num:  18, stage: 'GROUP', group:  'I', date: '2026-06-16', time: '18:00 UTC-4', venue: 'Boston (Foxborough)', home: 'IRQ', away: 'NOR' },
  { num:  19, stage: 'GROUP', group:  'J', date: '2026-06-16', time: '20:00 UTC-5', venue: 'Kansas City', home: 'ARG', away: 'ALG' },
  { num:  20, stage: 'GROUP', group:  'J', date: '2026-06-16', time: '21:00 UTC-7', venue: 'San Francisco Bay Area (Santa Clara)', home: 'AUT', away: 'JOR' },
  { num:  21, stage: 'GROUP', group:  'K', date: '2026-06-17', time: '12:00 UTC-5', venue: 'Houston', home: 'POR', away: 'COD' },
  { num:  22, stage: 'GROUP', group:  'L', date: '2026-06-17', time: '15:00 UTC-5', venue: 'Dallas (Arlington)', home: 'ENG', away: 'CRO' },
  { num:  23, stage: 'GROUP', group:  'L', date: '2026-06-17', time: '19:00 UTC-4', venue: 'Toronto', home: 'GHA', away: 'PAN' },
  { num:  24, stage: 'GROUP', group:  'K', date: '2026-06-17', time: '20:00 UTC-6', venue: 'Mexico City', home: 'UZB', away: 'COL' },
  { num:  25, stage: 'GROUP', group:  'A', date: '2026-06-18', time: '12:00 UTC-4', venue: 'Atlanta', home: 'CZE', away: 'RSA' },
  { num:  26, stage: 'GROUP', group:  'B', date: '2026-06-18', time: '12:00 UTC-7', venue: 'Los Angeles (Inglewood)', home: 'SUI', away: 'BIH' },
  { num:  27, stage: 'GROUP', group:  'B', date: '2026-06-18', time: '15:00 UTC-7', venue: 'Vancouver', home: 'CAN', away: 'QAT' },
  { num:  28, stage: 'GROUP', group:  'A', date: '2026-06-18', time: '19:00 UTC-6', venue: 'Guadalajara (Zapopan)', home: 'MEX', away: 'KOR' },
  { num:  29, stage: 'GROUP', group:  'D', date: '2026-06-19', time: '12:00 UTC-7', venue: 'Seattle', home: 'USA', away: 'AUS' },
  { num:  30, stage: 'GROUP', group:  'C', date: '2026-06-19', time: '18:00 UTC-4', venue: 'Boston (Foxborough)', home: 'SCO', away: 'MAR' },
  { num:  31, stage: 'GROUP', group:  'C', date: '2026-06-19', time: '20:30 UTC-4', venue: 'Philadelphia', home: 'BRA', away: 'HAI' },
  { num:  32, stage: 'GROUP', group:  'D', date: '2026-06-19', time: '20:00 UTC-7', venue: 'San Francisco Bay Area (Santa Clara)', home: 'TUR', away: 'PAR' },
  { num:  33, stage: 'GROUP', group:  'F', date: '2026-06-20', time: '12:00 UTC-5', venue: 'Houston', home: 'NED', away: 'SWE' },
  { num:  34, stage: 'GROUP', group:  'E', date: '2026-06-20', time: '16:00 UTC-4', venue: 'Toronto', home: 'GER', away: 'CIV' },
  { num:  35, stage: 'GROUP', group:  'E', date: '2026-06-20', time: '19:00 UTC-5', venue: 'Kansas City', home: 'ECU', away: 'CUW' },
  { num:  36, stage: 'GROUP', group:  'F', date: '2026-06-20', time: '22:00 UTC-6', venue: 'Monterrey (Guadalupe)', home: 'TUN', away: 'JPN' },
  { num:  37, stage: 'GROUP', group:  'H', date: '2026-06-21', time: '12:00 UTC-4', venue: 'Atlanta', home: 'ESP', away: 'KSA' },
  { num:  38, stage: 'GROUP', group:  'G', date: '2026-06-21', time: '12:00 UTC-7', venue: 'Los Angeles (Inglewood)', home: 'BEL', away: 'IRN' },
  { num:  39, stage: 'GROUP', group:  'H', date: '2026-06-21', time: '18:00 UTC-4', venue: 'Miami (Miami Gardens)', home: 'URU', away: 'CPV' },
  { num:  40, stage: 'GROUP', group:  'G', date: '2026-06-21', time: '18:00 UTC-7', venue: 'Vancouver', home: 'NZL', away: 'EGY' },
  { num:  41, stage: 'GROUP', group:  'J', date: '2026-06-22', time: '12:00 UTC-5', venue: 'Dallas (Arlington)', home: 'ARG', away: 'AUT' },
  { num:  42, stage: 'GROUP', group:  'I', date: '2026-06-22', time: '17:00 UTC-4', venue: 'Philadelphia', home: 'FRA', away: 'IRQ' },
  { num:  43, stage: 'GROUP', group:  'I', date: '2026-06-22', time: '20:00 UTC-4', venue: 'New York/New Jersey (East Rutherford)', home: 'NOR', away: 'SEN' },
  { num:  44, stage: 'GROUP', group:  'J', date: '2026-06-22', time: '20:00 UTC-7', venue: 'San Francisco Bay Area (Santa Clara)', home: 'JOR', away: 'ALG' },
  { num:  45, stage: 'GROUP', group:  'K', date: '2026-06-23', time: '12:00 UTC-5', venue: 'Houston', home: 'POR', away: 'UZB' },
  { num:  46, stage: 'GROUP', group:  'L', date: '2026-06-23', time: '16:00 UTC-4', venue: 'Boston (Foxborough)', home: 'ENG', away: 'GHA' },
  { num:  47, stage: 'GROUP', group:  'L', date: '2026-06-23', time: '19:00 UTC-4', venue: 'Toronto', home: 'PAN', away: 'CRO' },
  { num:  48, stage: 'GROUP', group:  'K', date: '2026-06-23', time: '20:00 UTC-6', venue: 'Guadalajara (Zapopan)', home: 'COL', away: 'COD' },
  { num:  49, stage: 'GROUP', group:  'B', date: '2026-06-24', time: '12:00 UTC-7', venue: 'Vancouver', home: 'SUI', away: 'CAN' },
  { num:  50, stage: 'GROUP', group:  'B', date: '2026-06-24', time: '12:00 UTC-7', venue: 'Seattle', home: 'BIH', away: 'QAT' },
  { num:  51, stage: 'GROUP', group:  'C', date: '2026-06-24', time: '18:00 UTC-4', venue: 'Miami (Miami Gardens)', home: 'SCO', away: 'BRA' },
  { num:  52, stage: 'GROUP', group:  'C', date: '2026-06-24', time: '18:00 UTC-4', venue: 'Atlanta', home: 'MAR', away: 'HAI' },
  { num:  53, stage: 'GROUP', group:  'A', date: '2026-06-24', time: '19:00 UTC-6', venue: 'Mexico City', home: 'CZE', away: 'MEX' },
  { num:  54, stage: 'GROUP', group:  'A', date: '2026-06-24', time: '19:00 UTC-6', venue: 'Monterrey (Guadalupe)', home: 'RSA', away: 'KOR' },
  { num:  55, stage: 'GROUP', group:  'E', date: '2026-06-25', time: '16:00 UTC-4', venue: 'Philadelphia', home: 'CUW', away: 'CIV' },
  { num:  56, stage: 'GROUP', group:  'E', date: '2026-06-25', time: '16:00 UTC-4', venue: 'New York/New Jersey (East Rutherford)', home: 'ECU', away: 'GER' },
  { num:  57, stage: 'GROUP', group:  'F', date: '2026-06-25', time: '18:00 UTC-5', venue: 'Dallas (Arlington)', home: 'JPN', away: 'SWE' },
  { num:  58, stage: 'GROUP', group:  'F', date: '2026-06-25', time: '18:00 UTC-5', venue: 'Kansas City', home: 'TUN', away: 'NED' },
  { num:  59, stage: 'GROUP', group:  'D', date: '2026-06-25', time: '19:00 UTC-7', venue: 'Los Angeles (Inglewood)', home: 'TUR', away: 'USA' },
  { num:  60, stage: 'GROUP', group:  'D', date: '2026-06-25', time: '19:00 UTC-7', venue: 'San Francisco Bay Area (Santa Clara)', home: 'PAR', away: 'AUS' },
  { num:  61, stage: 'GROUP', group:  'I', date: '2026-06-26', time: '15:00 UTC-4', venue: 'Boston (Foxborough)', home: 'NOR', away: 'FRA' },
  { num:  62, stage: 'GROUP', group:  'I', date: '2026-06-26', time: '15:00 UTC-4', venue: 'Toronto', home: 'SEN', away: 'IRQ' },
  { num:  63, stage: 'GROUP', group:  'H', date: '2026-06-26', time: '19:00 UTC-5', venue: 'Houston', home: 'CPV', away: 'KSA' },
  { num:  64, stage: 'GROUP', group:  'H', date: '2026-06-26', time: '18:00 UTC-6', venue: 'Guadalajara (Zapopan)', home: 'URU', away: 'ESP' },
  { num:  65, stage: 'GROUP', group:  'G', date: '2026-06-26', time: '20:00 UTC-7', venue: 'Seattle', home: 'EGY', away: 'IRN' },
  { num:  66, stage: 'GROUP', group:  'G', date: '2026-06-26', time: '20:00 UTC-7', venue: 'Vancouver', home: 'NZL', away: 'BEL' },
  { num:  67, stage: 'GROUP', group:  'L', date: '2026-06-27', time: '17:00 UTC-4', venue: 'New York/New Jersey (East Rutherford)', home: 'PAN', away: 'ENG' },
  { num:  68, stage: 'GROUP', group:  'L', date: '2026-06-27', time: '17:00 UTC-4', venue: 'Philadelphia', home: 'CRO', away: 'GHA' },
  { num:  69, stage: 'GROUP', group:  'K', date: '2026-06-27', time: '19:30 UTC-4', venue: 'Miami (Miami Gardens)', home: 'COL', away: 'POR' },
  { num:  70, stage: 'GROUP', group:  'K', date: '2026-06-27', time: '19:30 UTC-4', venue: 'Atlanta', home: 'COD', away: 'UZB' },
  { num:  71, stage: 'GROUP', group:  'J', date: '2026-06-27', time: '21:00 UTC-5', venue: 'Kansas City', home: 'ALG', away: 'AUT' },
  { num:  72, stage: 'GROUP', group:  'J', date: '2026-06-27', time: '21:00 UTC-5', venue: 'Dallas (Arlington)', home: 'JOR', away: 'ARG' },
  { num:  73, stage: 'R32', group: null, date: '2026-06-28', time: '12:00 UTC-7', venue: 'Los Angeles (Inglewood)', home: '2A', away: '2B' },
  { num:  74, stage: 'R32', group: null, date: '2026-06-29', time: '16:30 UTC-4', venue: 'Boston (Foxborough)', home: '1E', away: '3A/B/C/D/F' },
  { num:  75, stage: 'R32', group: null, date: '2026-06-29', time: '19:00 UTC-6', venue: 'Monterrey (Guadalupe)', home: '1F', away: '2C' },
  { num:  76, stage: 'R32', group: null, date: '2026-06-29', time: '12:00 UTC-5', venue: 'Houston', home: '1C', away: '2F' },
  { num:  77, stage: 'R32', group: null, date: '2026-06-30', time: '17:00 UTC-4', venue: 'New York/New Jersey (East Rutherford)', home: '1I', away: '3C/D/F/G/H' },
  { num:  78, stage: 'R32', group: null, date: '2026-06-30', time: '12:00 UTC-5', venue: 'Dallas (Arlington)', home: '2E', away: '2I' },
  { num:  79, stage: 'R32', group: null, date: '2026-06-30', time: '19:00 UTC-6', venue: 'Mexico City', home: '1A', away: '3C/E/F/H/I' },
  { num:  80, stage: 'R32', group: null, date: '2026-07-01', time: '12:00 UTC-4', venue: 'Atlanta', home: '1L', away: '3E/H/I/J/K' },
  { num:  81, stage: 'R32', group: null, date: '2026-07-01', time: '17:00 UTC-7', venue: 'San Francisco Bay Area (Santa Clara)', home: '1D', away: '3B/E/F/I/J' },
  { num:  82, stage: 'R32', group: null, date: '2026-07-01', time: '13:00 UTC-7', venue: 'Seattle', home: '1G', away: '3A/E/H/I/J' },
  { num:  83, stage: 'R32', group: null, date: '2026-07-02', time: '19:00 UTC-4', venue: 'Toronto', home: '2K', away: '2L' },
  { num:  84, stage: 'R32', group: null, date: '2026-07-02', time: '12:00 UTC-7', venue: 'Los Angeles (Inglewood)', home: '1H', away: '2J' },
  { num:  85, stage: 'R32', group: null, date: '2026-07-02', time: '20:00 UTC-7', venue: 'Vancouver', home: '1B', away: '3E/F/G/I/J' },
  { num:  86, stage: 'R32', group: null, date: '2026-07-03', time: '18:00 UTC-4', venue: 'Miami (Miami Gardens)', home: '1J', away: '2H' },
  { num:  87, stage: 'R32', group: null, date: '2026-07-03', time: '20:30 UTC-5', venue: 'Kansas City', home: '1K', away: '3D/E/I/J/L' },
  { num:  88, stage: 'R32', group: null, date: '2026-07-03', time: '13:00 UTC-5', venue: 'Dallas (Arlington)', home: '2D', away: '2G' },
  { num:  89, stage: 'R16', group: null, date: '2026-07-04', time: '17:00 UTC-4', venue: 'Philadelphia', home: 'W74', away: 'W77' },
  { num:  90, stage: 'R16', group: null, date: '2026-07-04', time: '12:00 UTC-5', venue: 'Houston', home: 'W73', away: 'W75' },
  { num:  91, stage: 'R16', group: null, date: '2026-07-05', time: '16:00 UTC-4', venue: 'New York/New Jersey (East Rutherford)', home: 'W76', away: 'W78' },
  { num:  92, stage: 'R16', group: null, date: '2026-07-05', time: '18:00 UTC-6', venue: 'Mexico City', home: 'W79', away: 'W80' },
  { num:  93, stage: 'R16', group: null, date: '2026-07-06', time: '14:00 UTC-5', venue: 'Dallas (Arlington)', home: 'W83', away: 'W84' },
  { num:  94, stage: 'R16', group: null, date: '2026-07-06', time: '17:00 UTC-7', venue: 'Seattle', home: 'W81', away: 'W82' },
  { num:  95, stage: 'R16', group: null, date: '2026-07-07', time: '12:00 UTC-4', venue: 'Atlanta', home: 'W86', away: 'W88' },
  { num:  96, stage: 'R16', group: null, date: '2026-07-07', time: '13:00 UTC-7', venue: 'Vancouver', home: 'W85', away: 'W87' },
  { num:  97, stage:  'QF', group: null, date: '2026-07-09', time: '16:00 UTC-4', venue: 'Boston (Foxborough)', home: 'W89', away: 'W90' },
  { num:  98, stage:  'QF', group: null, date: '2026-07-10', time: '12:00 UTC-7', venue: 'Los Angeles (Inglewood)', home: 'W93', away: 'W94' },
  { num:  99, stage:  'QF', group: null, date: '2026-07-11', time: '17:00 UTC-4', venue: 'Miami (Miami Gardens)', home: 'W91', away: 'W92' },
  { num: 100, stage:  'QF', group: null, date: '2026-07-11', time: '20:00 UTC-5', venue: 'Kansas City', home: 'W95', away: 'W96' },
  { num: 101, stage:  'SF', group: null, date: '2026-07-14', time: '14:00 UTC-5', venue: 'Dallas (Arlington)', home: 'W97', away: 'W98' },
  { num: 102, stage:  'SF', group: null, date: '2026-07-15', time: '15:00 UTC-4', venue: 'Atlanta', home: 'W99', away: 'W100' },
  { num: 103, stage:  '3P', group: null, date: '2026-07-18', time: '17:00 UTC-4', venue: 'Miami (Miami Gardens)', home: 'L101', away: 'L102' },
  { num: 104, stage:   'F', group: null, date: '2026-07-19', time: '15:00 UTC-4', venue: 'New York/New Jersey (East Rutherford)', home: 'W101', away: 'W102' },
];

export const GROUP_MATCHES = MATCHES.filter(m => m.stage === 'GROUP');
export const KO_MATCHES = MATCHES.filter(m => m.stage !== 'GROUP');
